export const actionTypes = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOG_OUT: "LOG_OUT",
  GET_POSTS: "GET_POSTS",
  GET_POST_LIMIT: "GET_POST_LIMIT",
  GET_PRICE: "GET_PRICE",
  GET_AREA: "GET_AREA",
  GET_POST_CONDITION: "GET_POST_CONDITION",
  GET_CATEGORY: "GET_CATEGORY",
  GET_POST_NEWREALISE: "GET_POST_NEWREALISE",
  GET_PROVINCE: "GET_PROVINCE",
  GET_USER : "GET_USER"
};
